platform:
  network_hardware:
    network_type: ethernet # wifi , ethernet , none
    ethernet_chip_select: 5 # イーサネットのチップセレクトピン番号
  rtc:
    rtc_type: PCF8523 # RTC8564NB , DS1307 , DS3231 , PCF8523 , RV8803 , RX8025 , RX8900 , none
    rtc_int_pin: 4  # ピン番号
  color_led: 
    use_led: true # true(使う) , false(使わない)
    led_data_pin: 7 # ピン番号
    led_clk_pin: 6 # ピン番号
    led_duration: 3000 # 時間(単位:ミリ秒)
    led_short_duration: 1000 # 時間(単位:ミリ秒)
  sd:
    use_sd: true # true(使う) , false(使わない)
    sd_chip_select: SDCARD_SS_PIN # ピン番号
  wdt:
    wdt_duration: 20000 # 時間(単位:ミリ秒)
    wdt_short_duration: 500 # 時間(単位:ミリ秒)

common:
  serial:
    speed: 9600 # コンソールのシリアル速度(bps)
  log:
    host_name: "MKR_Zero" # ホスト名(文字列)
    app_name: "AusEx_mqtt_client" # アプリ名(文字列)
    use_logfile: true # true(使う) , false(使わない)
    use_serial_log: true # true(使う) , false(使わない)
    logfile_name_hdr: "/syslog" # ログファイル名
    logfile_size_max: 10000000 # ログファイルの最大値(バイト)
    log_rotate: false # true(使う) , false(使わない) 現在未対応
  clock:
    use_ntp : false # true(使う) , false(使わない)
    update_rtc_by_ntp : false # true(使う) , false(使わない)

network:
  wifi:
    ssid: "Buffalo-G-9C50" # ssid名
    wifi_pass: "jxgdekvmujfyh" # wifiパスワード
  ethernet:
    mac_addr: [ '0x90', '0xa2', '0xda', '0x10', '0x11', '0x51']  # macアドレス
  ip:
    use_dhcp: true # true(使う) , false(使わない)
    ip_addr: [192, 168, 1, 111] # ipアドレス
    dns_server:  [192, 168, 1, 254] # DNSサーバ
    gateway: [192, 168, 1, 254] # gateway
    netmask: [255, 255, 255, 0] # マスク
  mqtt:
    mqtt_format: plain # plain, json, syslog
    mqtt_auth: false # true(使う) , false(使わない)
    mqtt_user: "foo" # ユーザ名(文字列)
    mqtt_pass: "bar" # パスワード(文字列)
    mqtt_topic: "arduino/echo" # MQTTトピック (文字列)
    mqtt_server: "192.168.1.254" # mqttサーバIPアドレス
    mqtt_port: 1883 # mqttポート番号

safety:
  use_wdt: true # true(使う) , false(使わない)

sensor:
  sensor_interval: 15000 # 測定間の待ち時間 (単位:ミリ秒)
  low_power:
    use_sleep: true # 待機中のsleep true(使う) , false(使わない)
    sleep_mode: power_down # idle, adc, power_save, standby, power_down

#
# DHTシリーズ温湿度計
#
dht:
  use_dht: true # true(使う) , false(使わない)
  dht_pin: 3
  dht_type: DHT22 # DHT11 , DHT21 , DHT22
  temperature_sensor_id: -1
  humidity_sensor_id: -1


